FROM python:3.11-slim
WORKDIR /app

# Устанавливаем зависимости
COPY ./backend/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Копируем код бэкенда
COPY ./backend .

# Копируем наш новый скрипт запуска
COPY entrypoint.sh .
RUN chmod +x ./entrypoint.sh # Делаем скрипт исполняемым

# Указываем, что контейнер будет запускаться через этот скрипт
ENTRYPOINT ["./entrypoint.sh"]