version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "5643:5643"
    volumes:
      - ./backend:/app
    command: uvicorn main:app --host 0.0.0.0 --port 5643 --reload

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
    command: npm run dev
