FROM python:3.11-slim

WORKDIR /app

COPY ./backend/requirements.txt .
RUN pip install --no-cache-dir --upgrade pip
RUN pip install --no-cache-dir -r requirements.txt

COPY ./backend .

CMD ["gunicorn", "-w", "4", "-k", "uvicorn.workers.UvicornWorker", "backend/main:app", "-b", "0.0.0.0:8000"]