"""Create users table

Revision ID: 53b89a98122c
Revises: 197e3ff4181c
Create Date: 2025-07-08 15:12:21.883894

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53b89a98122c'
down_revision: Union[str, Sequence[str], None] = '197e3ff4181c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('an_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('file_uid', sa.String(), nullable=False),
    sa.Column('datetime_created', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_an_files_file_uid'), 'an_files', ['file_uid'], unique=True)
    op.create_index(op.f('ix_an_files_id'), 'an_files', ['id'], unique=False)
    op.create_index(op.f('ix_an_files_user_id'), 'an_files', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_an_files_user_id'), table_name='an_files')
    op.drop_index(op.f('ix_an_files_id'), table_name='an_files')
    op.drop_index(op.f('ix_an_files_file_uid'), table_name='an_files')
    op.drop_table('an_files')
    # ### end Alembic commands ###
